version = "3.10.7"

runner.dialect = scala3

maxColumn = 100

newlines.source = keep
newlines.beforeCurlyLambdaParams = never
rewrite.insertBraces.minLines = 2
rewrite.insertBraces.allBlocks = true

danglingParentheses {
  callSite = true           # avoid aggressive line breaks around parens
  defnSite = true
}

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers
]

align.preset = some
assumeStandardLibraryStripMargin = true
